### ISSUE TITLE
Limited to last 50 episodes?

### ISSUE THREAD

**Issue by gkarthickraj** [timdorr/spotifeed#34] opened 2021-07-09 16:40 UTC
![image](https://user-images.githubusercontent.com/37563841/125110533-4fcdbe80-e102-11eb-8ee5-9fb886cf4f56.png)
Snapshot of the feed of 'The Joe Rogan Experience'.

**Comment by timdorr** [comment] 2021-07-10 17:57
This project is discontinued.

Duplicate of #8

**Closed by timdorr** 2021-07-10 17:57 UTC
